<?php
/**
 * Created by PhpStorm.
 * User: Yu
 * Date: 2017/10/15
 * Time: 17:03
 */
require_once "father_class.php";
//继承父类
class child_class extends father_class
{
    public function __construct($age,$name)
    {
        //把参数传给父类
        parent::__construct($age,$name,'男');


    }
    public function return_name()
    {
        echo '我是重写父类的该方法';

     //继承父类该方法可以： parent::return_name(); // TODO: Change the autogenerated stub
    }
}
?>